"""A complete investigation with no API key and no network.

Run it with:

    uv run python examples/minimal.py

FakeVLM plays the part of the model, so the output is identical on every
machine and every run. Swap in PydanticAIVLM("google:gemini-2.5-flash") to
point the same code at a real model.
"""

from PIL import Image, ImageDraw
from pydantic import BaseModel

from saccade import ActiveVisionAgent, Tool, ToolResult
from saccade.geometry.shapes import circles_overlap
from saccade.vlm import FakeVLM


class NoParams(BaseModel):
    """This tool measures the whole view, so it takes no arguments."""


# Two circles that genuinely overlap: centres 40px apart, radii 25 and 25.
CENTRE_A, RADIUS_A = (50.0, 50.0), 25.0
CENTRE_B, RADIUS_B = (90.0, 50.0), 25.0


def draw_two_circles() -> Image.Image:
    canvas = Image.new("RGB", (150, 100), "white")
    pen = ImageDraw.Draw(canvas)
    for (cx, cy), r in ((CENTRE_A, RADIUS_A), (CENTRE_B, RADIUS_B)):
        pen.ellipse([cx - r, cy - r, cx + r, cy + r], outline="black", width=2)
    return canvas


def overlap_tool() -> Tool:
    """The referee: geometry, not opinion.

    is_measurement=True is what lets this result contradict the model. A
    description generated by another model would have to be False.
    """

    def measure(image: object, viewport: object) -> ToolResult:
        return ToolResult(
            value={
                "method": "circles_overlap",
                "overlap": circles_overlap(CENTRE_A, RADIUS_A, CENTRE_B, RADIUS_B),
                "centre_distance": 40.0,
                "radius_sum": RADIUS_A + RADIUS_B,
            },
            is_measurement=True,
        )

    return Tool(
        name="circle_geometry",
        description="Compute whether the two circles overlap",
        fn=measure,
        params_schema=NoParams,
    )


def main() -> None:
    agent = ActiveVisionAgent(
        FakeVLM(["The two circles overlap near the middle."], exhausted="repeat_last"),
        tools=[overlap_tool()],
        confidence_threshold=0.7,
        max_steps=4,
    )

    result = agent.investigate(draw_two_circles(), "Do the two circles overlap?")

    print(f"answer:     {result.answer}")
    print(f"confidence: {result.confidence:.2f}")
    print(f"converged:  {result.converged}")
    print(f"steps:      {len(result.evidence_chain)}\n")

    for step in result.evidence_chain:
        box = step.viewport.bbox
        print(f"  [{step.index}] {step.action_name} at ({box.x}, {box.y}) {box.w}x{box.h}")
        print(f"      said:     {step.observation.statement}")
        if step.verification is not None:
            verdict = "confirmed" if step.verification.passed else "CONFLICT"
            print(f"      {verdict}: {step.verification.computed}")
            if step.verification.conflict:
                print(f"      reason:   {step.verification.conflict}")


if __name__ == "__main__":
    main()
